# 工作流程名称
name: Publish Python Package to PyPI

# 触发条件：当一个新的 Release 被发布时
on:
  release:
    types: [published]

# 工作流程任务
jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write # 这是可信发布的关键权限

    steps:
      # 第一步：检出（下载）你的代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- 新增的调试步骤 ---
      # 这一步会递归地列出所有文件，让我们能准确地看到 Actions "看到" 的文件结构是什么样的。
      - name: List files in the repository
        run: ls -R

      # 第三步：安装 Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      # 第四步：安装构建依赖
      - name: Install dependencies
        run: python -m pip install --upgrade pip build

      # 第五步：构建你的包
      # 这个命令会在仓库的根目录运行，它应该能直接找到 pyproject.toml
      - name: Build package
        run: python -m build

      # 第六步：发布到 PyPI
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1